# Name of workflow
name: Lint and Test workflow

# Trigger workflow on all pull requests
on:
  pull_request:
    branches:
      - develop
      - staging

# Jobs to carry out
jobs:
  # Name of action
  test:
    runs-on: ubuntu-latest

    # Steps in job
    steps:
      # Get code from repo
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Use Node.js 21.x
        uses: actions/setup-node@v1
        with:
          node-version: 21.x

      # Install Dependencies
      - name: Install Dependencies
        run: npm install

      # Run lint script
      - name: Run Lint
        run: npm run lint

      # Run build script
      - name: Run Build
        run: npm run build

      # Run test script
      - name: Run Tests
        run: npm run test
