# Name of workflow
name: Deploy to Render Test

# Trigger workflow on all pull requests
on:
  push:
    branches: [main]
  pull_request:
    branches:
      - main

# Jobs to carry out
jobs:
  # Name of action
  ci:
    runs-on: ubuntu-latest

    # Steps in job
    steps:
      - uses: actions/checkout@v3

      - name: Test
        run: |
          npm install
          npm run test

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        env:
          DEPLOY_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$DEPLOY_URL"
